# Generated by Django 4.1.1 on 2022-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0006_alter_cart_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_products',
            new_name='cart_product',
        ),
    ]
