# Generated by Django 4.1.1 on 2022-12-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0007_rename_cart_products_cart_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailapp.product'),
        ),
    ]
